### ISSUE TITLE
Make issues

### ISSUE THREAD

**Issue by Neotriple** [humanoid-path-planner/hpp-doc#28]
While compiling HPP, I am currently running into issues regarding during the step of 'make all' with the following error:

On Ubuntu 14.04
ROS Indigo

I am following the instructions at:

https://humanoid-path-planner.github.io/hpp-doc/download.html for Ubuntu 14.04

I believe this can be fixed with a simple --std=c++11 flag somewhere, however, I am unsure of the location of the compilation of the gepetto-viewer in the makefile as the gepetto-viewer makefile (in the gepetto-viewer subfolder) is overwritten when running 'make all' from the main folder as per instructions.

```
 Building CXX object src/CMakeFiles/gepetto-viewer.dir/urdf-parser.cpp.o
cd /Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel/src && /usr/bin/c++   -Dgepetto_viewer_EXPORTS -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG -fPIC -I/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel -I/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel/include -I/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/include -isystem /Network/Servers/duerer/Volumes/duerer/paarth/HPP/install/include -isystem /usr/local/include    -o CMakeFiles/gepetto-viewer.dir/urdf-parser.cpp.o -c /Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/src/urdf-parser.cpp
/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/src/urdf-parser.cpp:29:16: error: ‘std::shared_ptr’ has not been declared
     using std::shared_ptr;
                ^
/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/src/urdf-parser.cpp:30:16: error: ‘std::weak_ptr’ has not been declared
     using std::weak_ptr;
                ^
make[3]: *** [src/CMakeFiles/gepetto-viewer.dir/urdf-parser.cpp.o] Error 1
make[3]: Leaving directory `/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel'
make[2]: *** [src/CMakeFiles/gepetto-viewer.dir/all] Error 2
make[2]: Leaving directory `/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel'
make: *** [gepetto-viewer.install] Error 2

```

**Comment by nim65s** [comment]
Hi,

HPP is not really tested on 14.04 anymore on the main branches, but you should be able to get it work on the ubuntu-14.04 branches.

Did you followed the instructions given here https://humanoid-path-planner.github.io/hpp-doc/download.html on "Stable - Ubuntu 14.04" ?

**Comment by nim65s** [comment]
Hi,

According to http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021 ros Kinetic is not supported on Ubuntu 14.04.
Can you try with ROS Indigo ?

**Comment by jmirabel** [comment]
Can you check what version of urdfdom you have: `pkg-config --modversion urdfdom`

**Comment by Neotriple** [comment]
1.0.0

**Comment by jmirabel** [comment]
I might be wrong but I think this is not the version package in Ubuntu 14.04.

**Comment by Neotriple** [comment]
Hmm, interesting. Does this command check for the version of liburdfdom-dev or some other package?

If I do apt-get installed to check the version, I get the following for the urdf packages:

ros-indigo-urdf/trusty,now 1.11.15-1trusty-20180317-024607-0800 amd64 [installed,automatic]
ros-indigo-urdf-parser-plugin/trusty,now 1.11.15-1trusty-20171113-102812-0800 amd64 [installed,automatic]
ros-indigo-urdf-tutorial/trusty,now 0.3.0-0trusty-20180724-044857-0800 amd64 [installed,auto-removable]
ros-indigo-urdfdom-py/trusty,now 0.3.3-1trusty-20170313-051022-0700 amd64 [installed,automatic]

liburdfdom-dev/trusty,now 0.2.10+dfsg-1 amd64 [installed]
liburdfdom-headers-dev/now 20180912-1 amd64 [installed,local]

So it seems the liburdfdom-dev version is actually 0.2.10 which seems to be compliant with the following site:

https://packages.ubuntu.com/hu/source/trusty/urdfdom

**Comment by Neotriple** [comment]
Not sure if this is related, but for the command:

make robot_state_chain_publisher.install;

to work, I did have to follow the instructions at the following site which involved changing my version of ros-urdfdom:

https://answers.ros.org/question/243756/ros-indigo-install-on-rpi3-urdf-compile-errors/

**Comment by jmirabel** [comment]
I think it matters. You should probably remove it.

Command `locate urdfdom.pc` will tell you where is the faulty installation of urdfdom.

**Comment by Neotriple** [comment]
Deleted the urdfdom.pc with version 1.0.0, and now I receive the following error:

```
[ 60%] Building CXX object src/CMakeFiles/gepetto-viewer.dir/urdf-parser.cpp.o
cd /Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel/src && /usr/bin/c++   -DURDFDOM_BOOST_SHARED_PTR -DURDFDOM_POINTER_CAST -Dgepetto_viewer_EXPORTS -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG -fPIC -I/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel -I/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel/include -I/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/include -isystem /usr/local/include    -o CMakeFiles/gepetto-viewer.dir/urdf-parser.cpp.o -c /Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/src/urdf-parser.cpp
/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/src/urdf-parser.cpp:46:16: error: ‘static_pointer_cast’ is already declared in this scope
   using boost::static_pointer_cast;
                ^
make[3]: *** [src/CMakeFiles/gepetto-viewer.dir/urdf-parser.cpp.o] Error 1
make[3]: Leaving directory `/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel'
make[2]: *** [src/CMakeFiles/gepetto-viewer.dir/all] Error 2
make[2]: Leaving directory `/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/Network/Servers/duerer/Volumes/duerer/paarth/HPP/src/gepetto-viewer/build-rel'
make: *** [gepetto-viewer.install] Error 2

```

**Comment by jmirabel** [comment]
I meant deleting the whole urdfdom installation. See install_manifest.txt in the build folder of urdfdom.

And do not forget to remove the CMakeCache.txt in the build folder of gepetto-viewer.

**Comment by jmirabel** [comment]
I close the issue due to inactivity. Re-open if necessary.
